services:
  db:
    image: mysql:8.0
    container_name: my-mysql-main
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    networks:
      - mainnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "8000:80"
    networks:
      - mainnet

networks:
  mainnet:
    external: true
